version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_zup
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
    ports:
      - "3306:3306"
    volumes:
      - zup_data:/var/lib/mysql

volumes:
  zup_data: